apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: andressaffdiniz/nginx-test
    argocd-image-updater.argoproj.io/update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: develop
spec:
  project: default
  source:
    repoURL: 'https://github.com/Andressa172/argocd-image-updater.git'
    targetRevision: develop
    path: manifests/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
